import Header from "./components/Header";
import "./globals.css";
import { Maven_Pro } from "next/font/google";

const maven_Pro = Maven_Pro({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "ManageHer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${maven_Pro.className} `}>
        <div className="header relative">
          <Header />
        </div>
        <div className="container mx-auto">{children}</div>
        <img
          src="
      assets/footer.gif"
          className="w-[650px] mx-auto"
          alt=""
        />
        <p className="text-center text-xl mb-5">Copyright @ 2023</p>
      </body>
    </html>
  );
}
