import Header from "./components/Header";
import "./globals.css";
import { Maven_Pro } from "next/font/google";

const maven_Pro = Maven_Pro({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${maven_Pro.className} max-w-7xl mx-auto px-4 sm:px-6 lg:px-8`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
